const world = {
  category: 3,
  closedAt: 2145938400,
  id: 150486,
  isUnlocked: true,
  name: 'Tyranny of the Impure (FF T)',
  openedAt: 1531357200,
  seriesId: 150001,
};

const dungeon = {
  name: 'Tyranny of the Impure, Part 3',
  id: 15048603,
  seriesId: 150001,
  difficulty: 0,
  openedAt: 1531357200,
  closedAt: 2145938400,
  isUnlocked: true,
  isComplete: true,
  isMaster: false,
  totalStamina: 1,
  staminaList: [1],
  prizes: {
    completion: [
      {
        id: 92000000,
        name: 'Gil',
        amount: 1500,
        type: 'common',
      },
    ],
    firstTime: [
      {
        id: 95001080,
        name: 'Record Rubies',
        amount: 20,
        type: 'common',
      },
      {
        id: 92000000,
        name: 'Gil',
        amount: 200000,
        type: 'common',
      },
      {
        id: 91000000,
        name: 'Mythril',
        amount: 1,
        type: 'common',
      },
    ],
    mastery: [
      {
        id: 40000066,
        name: 'Power Crystal',
        amount: 8,
        type: 'ability_material',
      },
      {
        id: 40000060,
        name: 'Major Holy Orb',
        amount: 10,
        type: 'ability_material',
      },
      {
        id: 92000000,
        name: 'Gil',
        amount: 200000,
        type: 'common',
      },
    ],
    claimedGrade: [
      {
        id: 95001080,
        name: 'Record Rubies',
        amount: 10,
        type: 'common',
      },
      {
        id: 130100300,
        name: 'Spirit Mote (5★)',
        amount: 20,
        type: 'sphere_material',
      },
      {
        id: 40000073,
        name: 'Ice Crystal',
        amount: 4,
        type: 'ability_material',
      },
      {
        id: 95001080,
        name: 'Record Rubies',
        amount: 10,
        type: 'common',
      },
      {
        id: 130100300,
        name: 'Spirit Mote (5★)',
        amount: 20,
        type: 'sphere_material',
      },
      {
        id: 40000072,
        name: 'Fire Crystal',
        amount: 4,
        type: 'ability_material',
      },
      {
        id: 95001080,
        name: 'Record Rubies',
        amount: 20,
        type: 'common',
      },
      {
        id: 130100300,
        name: 'Spirit Mote (5★)',
        amount: 25,
        type: 'sphere_material',
      },
    ],
    unclaimedGrade: [
      {
        id: 95001080,
        name: 'Record Rubies',
        amount: 40,
        type: 'common',
      },
      {
        id: 130100300,
        name: 'Spirit Mote (5★)',
        amount: 25,
        type: 'sphere_material',
      },
      {
        id: 95001080,
        name: 'Record Rubies',
        amount: 40,
        type: 'common',
      },
      {
        id: 92000000,
        name: 'Gil',
        amount: 200000,
        type: 'common',
      },
      {
        id: 95001080,
        name: 'Record Rubies',
        amount: 40,
        type: 'common',
      },
      {
        id: 92000000,
        name: 'Gil',
        amount: 200000,
        type: 'common',
      },
      {
        id: 95001080,
        name: 'Record Rubies',
        amount: 40,
        type: 'common',
      },
      {
        id: 130100300,
        name: 'Spirit Mote (5★)',
        amount: 25,
        type: 'sphere_material',
      },
      {
        id: 95001080,
        name: 'Record Rubies',
        amount: 40,
        type: 'common',
      },
      {
        id: 40000078,
        name: 'Dark Crystal',
        amount: 4,
        type: 'ability_material',
      },
      {
        id: 130100300,
        name: 'Spirit Mote (5★)',
        amount: 25,
        type: 'sphere_material',
      },
      {
        id: 95001080,
        name: 'Record Rubies',
        amount: 10,
        type: 'common',
      },
      {
        id: 130100300,
        name: 'Spirit Mote (5★)',
        amount: 20,
        type: 'sphere_material',
      },
      {
        id: 40000075,
        name: 'Earth Crystal',
        amount: 4,
        type: 'ability_material',
      },
      {
        id: 95001080,
        name: 'Record Rubies',
        amount: 10,
        type: 'common',
      },
      {
        id: 40000074,
        name: 'Lightning Crystal',
        amount: 4,
        type: 'ability_material',
      },
      {
        id: 130100300,
        name: 'Spirit Mote (5★)',
        amount: 20,
        type: 'sphere_material',
      },
    ],
  },
};
